version: '3'

services:
  replacer:
    build:
      dockerfile: replacer.dockerfile
      args:
        - HOST=${HOST}
        - YAMLURL=${YAMLURL}
    volumes:
      - config_data:/dockertmp

  prometheus:
    image: prom/prometheus
    depends_on:
      - replacer
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    # ports:
    #   - 9090:9090
    restart: unless-stopped
    volumes:
      - config_data:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    # ports:
    #   - "3000:3000"

volumes:
  prom_data:
  config_data:
