version: '3'

services:
  replacer:
    build:
      dockerfile: replacer.dockerfile
      args:
        - HOST=${HOST}
        - YAMLURL=${YAMLURL}
    volumes:
      - ${PWD}/config/prometheus.yml:/prometheus.yml

  prometheus:
    image: prom/prometheus
    depends_on:
      - replacer
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    # ports:
    #   - 9090:9090
    restart: unless-stopped
    volumes:
      - ${PWD}/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    # ports:
    #   - "3000:3000"

volumes:
  prom_data:
