services:
  replacer:
    build:
      dockerfile: replacer.dockerfile
      args:
        - HOST=${HOST}
  volumes:
    - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml

  prometheus:
    image: prom/prometheus
    depends-on:
      - replacer
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    # ports:
    #   - 9090:9090
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    # ports:
    #   - "3000:3000"

volumes:
  prom_data:
